import { useEffect, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, Ambulance, BarChart3, Bell, ChevronLeft, ChevronRight,
  ClipboardCheck, Clock3, FileClock, HeartPulse, Home, ListFilter,
  Map, Menu, Network, Pause, Play, RotateCcw, Search, Settings2, ShieldCheck,
  Smartphone, Stethoscope, Users, X, Check, Radio, Thermometer, Wind,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { SignalBadge, MachineMark } from "./SignalBadge";
import { TrendChart } from "./TrendChart";
import { patients, primaryPatient, network, regions, roles, scenarios, statusMeta, type Patient, type Signal } from "@/lib/lantern-data";
import { cn } from "@/lib/utils";
import { OperationalDrilldown, type MetricView } from "./OperationalDrilldown";

type View = "network"|"queue"|"patient"|"alert"|"handover"|"patientapp"|"observation"|"scenarios"|"governance"|"users"|"emergency"|"admission"|MetricView;

const navigation: Array<{id:View;label:string;icon:typeof Home;section?:string}> = [
  {id:"network",label:"Network command",icon:Network},
  {id:"queue",label:"Clinical queue",icon:ClipboardCheck},
  {id:"patient",label:"Patient record",icon:HeartPulse},
  {id:"alert",label:"Alert review",icon:Bell},
  {id:"handover",label:"Escalation",icon:Ambulance},
  {id:"admission",label:"Admission & discharge",icon:FileClock,section:"Care operations"},
  {id:"patientapp",label:"Patient app",icon:Smartphone},
  {id:"observation",label:"Observation capture",icon:Activity},
  {id:"scenarios",label:"Scenario control",icon:Play,section:"Prototype"},
  {id:"governance",label:"Governance",icon:ShieldCheck},
  {id:"users",label:"Users & access",icon:Users},
  {id:"emergency",label:"Emergency portal",icon:Ambulance},
];

export function RatanaApp() {
  const [view,setView] = useState<View>("network");
  const [selected,setSelected] = useState<Patient>(primaryPatient);
  const [role,setRole] = useState(roles[0]);
  const [mobileNav,setMobileNav] = useState(false);
  const [notice,setNotice] = useState("");
  const [auditEvents,setAuditEvents] = useState<Array<[string,string,string,string,string]>>([]);

  useEffect(() => { if (!notice) return; const id=window.setTimeout(()=>setNotice(""),3200); return()=>window.clearTimeout(id); },[notice]);

  const openPatient=(p:Patient,next:View="patient")=>{setSelected(p);setView(next);setMobileNav(false)};
  const audit=(event:string,detail:string)=>setAuditEvents(current=>{const entry:[string,string,string,string,string]=["08:49:30","Noah Williams",event,detail,"Console"];return [entry,...current].slice(0,8);});
  const openMetric=(metric:MetricView,filter?:string)=>{setView(metric);audit("dashboard_metric_card_clicked",`${metric}${filter?` · ${filter}`:""}`);setAuditEvents(current=>{const entry:[string,string,string,string,string]=["08:49:31","Noah Williams","dashboard_metric_drilldown_viewed",metric,"Console"];return [entry,...current].slice(0,8);});};
  const isPatientSurface=view==="patientapp"||view==="observation";

  if (isPatientSurface) return <PatientSurface view={view} onView={setView} onExit={()=>setView("network")} notify={setNotice} />;
  return <div className="min-h-screen bg-background text-foreground">
    <a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:bg-primary focus:px-4 focus:py-2 focus:text-primary-foreground">Skip to main content</a>
    <header className="sticky top-0 z-30 flex h-14 items-center border-b border-border bg-card px-4 lg:px-6">
      <Button variant="ghost" size="icon" className="mr-2 lg:hidden" onClick={()=>setMobileNav(true)} aria-label="Open navigation"><Menu /></Button>
      <Brand />
      <div className="ml-5 hidden border-l border-border pl-5 text-xs text-muted-foreground md:block">National command · <span className="font-medium text-foreground">Morning shift</span></div>
      <div className="ml-auto flex items-center gap-2">
        <div className="hidden text-right text-xs sm:block"><div className="font-semibold">Noah Williams</div><div className="text-muted-foreground">{role}</div></div>
      </div>
    </header>
    <div className="flex min-h-[calc(100vh-56px)]">
      <aside className={cn("fixed inset-y-0 left-0 z-40 w-72 border-r border-sidebar-border bg-sidebar p-3 transition-transform lg:sticky lg:top-14 lg:h-[calc(100vh-56px)] lg:w-60 lg:translate-x-0",mobileNav?"translate-x-0":"-translate-x-full")}>
        <div className="mb-3 flex h-11 items-center justify-between lg:hidden"><Brand/><Button variant="ghost" size="icon" onClick={()=>setMobileNav(false)} aria-label="Close navigation"><X/></Button></div>
        <Nav view={view} onView={(v)=>{setView(v);setMobileNav(false)}} />
        <div className="absolute inset-x-3 bottom-3 border-t border-sidebar-border pt-3">
          <label className="mb-1 block text-[11px] font-semibold uppercase text-muted-foreground">View as</label>
          <select value={role} onChange={e=>setRole(e.target.value)} className="h-11 w-full rounded-control border border-input bg-background px-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring">
            {roles.map(r=><option key={r}>{r}</option>)}
          </select>
        </div>
      </aside>
      {mobileNav&&<button className="fixed inset-0 z-30 bg-foreground/20 lg:hidden" onClick={()=>setMobileNav(false)} aria-label="Close navigation overlay" />}
      <main id="main" className="min-w-0 flex-1">
        {view==="network"&&<NetworkView onOpen={openPatient} onQueue={()=>setView("queue")} onMetric={openMetric} />}
        {view==="queue"&&<QueueView onOpen={openPatient} />}
        {view==="patient"&&<PatientView patient={selected} onView={setView} notify={setNotice} />}
        {view==="alert"&&<AlertView patient={selected} onView={setView} notify={setNotice} />}
        {view==="handover"&&<HandoverView patient={selected} onView={setView} notify={setNotice} />}
        {view==="scenarios"&&<ScenariosView notify={setNotice} onOpen={()=>openPatient(primaryPatient)} />}
        {view==="governance"&&<GovernanceView auditEvents={auditEvents} />}
        {view==="users"&&<UsersView notify={setNotice} />}
        {view==="emergency"&&<EmergencyView patient={selected} notify={setNotice} />}
        {view==="admission"&&<AdmissionView notify={setNotice} />}
        {(["admissions","transfers","devices","pressure","forecast"] as const).includes(view as MetricView)&&<OperationalDrilldown metric={view as MetricView} onBack={()=>setView("network")} notify={setNotice} audit={audit}/>} 
      </main>
    </div>
    {notice&&<div role="status" aria-live="polite" className="fixed bottom-5 right-5 z-50 flex max-w-sm items-center gap-3 border border-primary bg-card px-4 py-3 text-sm"><Check className="size-4 text-primary"/>{notice}</div>}
  </div>;
}

function Brand(){return <div className="flex items-center gap-2.5"><svg className="size-7 shrink-0 text-primary" viewBox="0 0 40 40" aria-hidden="true" fill="none"><path d="M6 35V17.5C6 9.9 12.3 4 20 4s14 5.9 14 13.5V35" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round"/><path d="M13 35V19.5a7 7 0 0 1 14 0V35" stroke="currentColor" strokeWidth="1.4" opacity=".45" strokeLinecap="round"/><circle cx="20" cy="21" r="3.6" fill="currentColor"/><path d="M20 4V1" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round"/></svg><span className="font-display text-xl font-semibold text-night dark:text-foreground">Rātana</span></div>}

function Nav({view,onView}:{view:View;onView:(v:View)=>void}){return <nav aria-label="Main navigation" className="space-y-0.5">
  {navigation.map((item,i)=>{const Icon=item.icon;return <div key={item.id}>{item.section&&<div className={cn("mb-1 mt-4 px-3 text-[11px] font-semibold uppercase text-muted-foreground",i===0&&"mt-0")}>{item.section}</div>}<Button variant="ghost" onClick={()=>onView(item.id)} className={cn("h-10 w-full justify-start px-3 font-normal",view===item.id&&"bg-sidebar-accent font-semibold text-primary")}><Icon className="size-4"/>{item.label}</Button></div>})}
</nav>}

function PageHead({eyebrow,title,summary,actions}:{eyebrow:string;title:string;summary:string;actions?:React.ReactNode}){return <div className="flex flex-col gap-4 border-b border-border bg-card px-5 py-5 sm:flex-row sm:items-end sm:justify-between lg:px-8"><div><div className="mb-1 text-[11px] font-semibold uppercase text-primary">{eyebrow}</div><h1 className="font-display text-3xl font-semibold leading-tight">{title}</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{summary}</p></div>{actions&&<div className="flex shrink-0 gap-2">{actions}</div>}</div>}

function Metric({label,value,detail,tone,onClick}:{label:string;value:string;detail:string;tone?:Signal;onClick?:()=>void}){const classes=cn("border border-border bg-card p-4 text-left",tone&&`border-l-2 ${statusMeta[tone].classes}`,onClick&&"group relative min-h-28 w-full cursor-pointer transition-colors hover:border-primary hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 active:bg-muted");const content=<><div className="text-[11px] font-semibold uppercase text-muted-foreground">{label}</div><div className="mt-2 font-mono text-3xl font-medium tabular-nums">{value}</div><div className="mt-1 pr-6 text-xs text-muted-foreground">{detail}</div>{onClick&&<ChevronRight className="absolute bottom-3 right-3 size-4 text-muted-foreground transition-transform group-hover:translate-x-0.5 group-hover:text-primary"/>}</>;return onClick?<button type="button" onClick={onClick} aria-label={`Open ${label.toLowerCase()} worklist`} className={classes}>{content}</button>:<div className={classes}>{content}</div>}

function NetworkView({onOpen,onQueue,onMetric}:{onOpen:(p:Patient)=>void;onQueue:()=>void;onMetric:(metric:MetricView,filter?:string)=>void}){return <>
  <PageHead eyebrow="Network command" title="5,000 active monitored patients" summary={`Sunday 13 September 2026 · 08:49 AEST · ${network.occupancyPercent}% virtual-bed occupancy · All six regions reporting`} actions={<><Button variant="outline"><ListFilter/>Filters</Button><Button onClick={onQueue}>Open clinical queue<ChevronRight/></Button></>}/>
  <div className="space-y-6 p-5 lg:p-8">
    <section className="grid grid-cols-2 gap-3 xl:grid-cols-6" aria-label="Network summary">
      <Metric label="Active monitored patients" value="5,000" detail={`${network.occupancyPercent}% virtual-bed occupancy`}/><Metric label="Stable" value="3,000" detail="60% of active patients" tone="stable"/><Metric label="Clinical review" value="1,000" detail="47 due < 30 min" tone="review"/><Metric label="Rapid response" value="402" detail="12 unowned · urgent load" tone="rapid"/><Metric label="No data" value="400" detail="31 overdue > 2 h" tone="nodata"/><Metric label="Likely discharges" value="209" detail="Next 24 hours"/>
    </section>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.7fr)]">
      <div className="border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-4"><div><h2 className="font-semibold">Regional operating picture</h2><p className="text-xs text-muted-foreground">Active monitored patients, clinical state and service pressure</p></div><Map className="size-5 text-primary"/></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-muted text-[11px] uppercase text-muted-foreground"><tr><th className="px-4 py-2.5">Region</th><th>Active patients</th><th>Review</th><th>Rapid</th><th>No data</th><th>Adm. pending</th><th>Pressure</th><th></th></tr></thead><tbody>{regions.map(r=><tr key={r.name} className="h-14 border-t border-border"><td className="px-4 font-semibold">{r.name}</td><td className="font-mono tabular-nums">{r.active.toLocaleString()}<div className="text-[11px] text-muted-foreground">{network.occupancyPercent}% occupied</div></td><td className="font-mono">▲ {r.review}</td><td className="font-mono">⬢ {r.rapid}</td><td className="font-mono">◌ {r.nodata}</td><td className="font-mono">{r.admissionsPending}</td><td><span className="font-mono">{r.pressure}%</span></td><td><Button variant="ghost" size="icon" aria-label={`Open ${r.name}`}><ChevronRight/></Button></td></tr>)}</tbody></table></div>
      </div>
      <div className="border border-border bg-card"><div className="border-b border-border p-4"><MachineMark verb="Ranked"/><h2 className="mt-2 font-semibold">Needs attention now</h2><p className="text-xs text-muted-foreground">Transparent priority order · NEWS2-like prototype score</p></div>{patients.slice(0,4).map(p=><button key={p.id} onClick={()=>onOpen(p)} className={cn("block w-full border-b border-border border-l-2 p-4 text-left hover:bg-accent",statusMeta[p.status].classes)}><div className="flex justify-between gap-3"><div><div className="font-semibold">{p.name}</div><div className="text-xs text-muted-foreground">{p.region} · {p.diagnosis}</div></div><div className="font-mono text-xl">{p.score}</div></div><p className="mt-2 text-xs leading-relaxed">{p.reason}</p><div className="mt-3 flex items-center justify-between"><SignalBadge signal={p.status}/><span className="font-mono text-[11px] text-muted-foreground">{p.observed}</span></div></button>)}</div>
    </section>
    <section className="grid gap-3 md:grid-cols-3 xl:grid-cols-5" aria-label="Operational worklists"><Metric label="Admissions pending" value={String(network.admissionsPending)} detail="23 awaiting first observation" onClick={()=>onMetric("admissions")}/><Metric label="Transfers in progress" value={String(network.transfersInProgress)} detail="Median handover 11 min" onClick={()=>onMetric("transfers")}/><Metric label="Device concerns" value={String(network.deviceConcerns)} detail="16 require contact" onClick={()=>onMetric("devices")}/><Metric label="Service pressure" value={network.servicePressure} detail={`Staffing headroom ${network.staffingHeadroom.toLowerCase()}`} onClick={()=>onMetric("pressure")}/><Metric label="Workload forecast" value={network.workload.h4.toLocaleString()} detail={`Next 4 h · 8 h ${network.workload.h8.toLocaleString()} · 24 h ${network.workload.h24.toLocaleString()}`} onClick={()=>onMetric("forecast")}/></section>
  </div>
</>}

function QueueView({onOpen}:{onOpen:(p:Patient)=>void}){const [filter,setFilter]=useState<Signal|"all">("all");const shown=filter==="all"?patients:patients.filter(p=>p.status===filter);return <><PageHead eyebrow="Clinical operations" title="Clinical queue" summary="Ranked by concern. Machine ranking never replaces clinical judgement." actions={<Button variant="outline"><Search/>Find patient</Button>}/><div className="p-5 lg:p-8"><div className="mb-4 flex flex-wrap items-center gap-2"><MachineMark verb="Ranked" confidence="High"/>{(["all","rapid","review","nodata","stable"] as const).map(f=><Button key={f} size="sm" variant={filter===f?"default":"outline"} onClick={()=>setFilter(f)}>{f==="all"?"All patients":statusMeta[f].label}</Button>)}</div><div className="overflow-x-auto border border-border bg-card"><table className="w-full min-w-[960px] text-left text-sm"><thead className="bg-muted text-[11px] uppercase text-muted-foreground"><tr><th className="px-4 py-3">Patient</th><th>Clinical state</th><th>Reason</th><th>Latest observations</th><th>Due</th><th>Owner</th><th></th></tr></thead><tbody>{shown.map(p=><tr key={p.id} className={cn("h-[72px] border-t border-border border-l-2 hover:bg-accent",statusMeta[p.status].classes)}><td className="px-4"><button className="text-left font-semibold hover:underline" onClick={()=>onOpen(p)}>{p.name}</button><div className="font-mono text-[11px] text-muted-foreground">{p.id} · {p.pathway}</div></td><td><SignalBadge signal={p.status}/></td><td className="max-w-xs text-xs">{p.reason}<div className="mt-1"><MachineMark verb="Detected" confidence={p.status==="rapid"?"High":"Moderate"}/></div></td><td className="font-mono text-xs">SpO₂ {p.spo2??"—"}% · RR {p.rr??"—"}<div className="text-muted-foreground">{p.observed}</div></td><td className="font-mono text-xs">{p.status==="rapid"?"Now":p.status==="review"?"09:05":"09:30"}</td><td className="text-xs">{p.owner}</td><td><Button variant="ghost" size="icon" onClick={()=>onOpen(p)} aria-label={`Open ${p.name}`}><ChevronRight/></Button></td></tr>)}</tbody></table></div></div></>}

function PatientView({patient,onView,notify}:{patient:Patient;onView:(v:View)=>void;notify:(s:string)=>void}){const [ack,setAck]=useState(false);return <>{patient.status==="rapid"&&<div role="alert" aria-live="assertive" className="flex flex-wrap items-center gap-3 border-b border-rapid bg-rapid-soft px-5 py-3 text-sm text-rapid lg:px-8"><AlertTriangle className="size-5"/><strong>Rapid response · observations outside pathway range</strong><span className="text-foreground">Escalation remains active until acknowledged.</span><Button className="ml-auto" variant="destructive" onClick={()=>{setAck(true);notify("Rapid response acknowledged by Noah Williams at 08:49 AEST")}} disabled={ack}>{ack?"Acknowledged 08:49":"Acknowledge alert"}</Button></div>}
  <PageHead eyebrow={`${patient.id} · ${patient.region}`} title={patient.name} summary={`${patient.age} years · ${patient.pronouns} · ${patient.diagnosis} · ${patient.pathway}`} actions={<><Button variant="outline" onClick={()=>onView("queue")}><ChevronLeft/>Queue</Button><Button onClick={()=>onView("handover")}><Ambulance/>Prepare transfer</Button></>}/>
  <div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1.4fr)_360px] lg:p-8"><div className="space-y-5"><section className="grid grid-cols-2 gap-3 md:grid-cols-5"><Vital label="SpO₂" value={patient.spo2?`${patient.spo2} %`:'—'} signal={patient.status}/><Vital label="Resp. rate" value={patient.rr?`${patient.rr} /min`:'—'} signal={patient.status==="nodata"?"nodata":patient.rr&&patient.rr>24?"rapid":"stable"}/><Vital label="Heart rate" value={patient.hr?`${patient.hr} bpm`:'—'} signal={patient.status==="nodata"?"nodata":patient.hr&&patient.hr>105?"review":"stable"}/><Vital label="Blood pressure" value={patient.bp?`${patient.bp} mmHg`:'—'} signal={patient.status==="nodata"?"nodata":"stable"}/><Vital label="Temperature" value={patient.temp?`${patient.temp} °C`:'—'} signal={patient.status==="nodata"?"nodata":patient.temp&&patient.temp>=38?"review":"stable"}/></section><section className="border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-4"><div><h2 className="font-semibold">SpO₂ trend</h2><p className="text-xs text-muted-foreground">24-hour pathway view · raw device observations</p></div><SignalBadge signal={patient.status}/></div><div className="p-4"><TrendChart/></div></section><MachinePanel patient={patient}/><section className="border border-border bg-card"><div className="border-b border-border p-4"><h2 className="font-semibold">Care timeline</h2></div>{["08:42 · Device reading received · SpO₂ 88%","08:43 · Composite score recalculated · 82 / 100","08:44 · Rapid response created · Dr Asha Rao notified","08:47 · Repeat observation requested · awaiting response"].map((t,i)=><div key={t} className="flex gap-3 border-b border-border p-3 text-sm last:border-0"><span className={cn("mt-1 size-2 shrink-0 rounded-full",i===2?"bg-rapid":"bg-primary")}/>{t}</div>)}</section></div><aside className="space-y-4"><Panel title="Current plan"><InfoRow k="Named owner" v={patient.owner}/><InfoRow k="Review due" v={patient.status==="rapid"?"Now":"09:05 AEST"}/><InfoRow k="Monitoring" v="Every 4 hours"/><InfoRow k="Last contact" v="08:18 AEST · Video"/><Button className="mt-4 w-full" onClick={()=>onView("alert")}>Review active alert<ChevronRight/></Button></Panel><Panel title="Care team"><InfoRow k="Consultant" v="Dr Asha Rao"/><InfoRow k="Visiting nurse" v="Mia Chen"/><InfoRow k="Coordinator" v="Luca Patel"/><InfoRow k="Pharmacy" v="Metro South Hub"/></Panel><Panel title="Device provenance"><InfoRow k="Pulse oximeter" v="LN-SP02-0418"/><InfoRow k="Paired" v="10 Sep 2026"/><InfoRow k="Signal quality" v="Good"/><Button variant="outline" className="mt-4 w-full" onClick={()=>notify("Raw observation stream opened")}>View raw data</Button></Panel></aside></div>
</>}

function Vital({label,value,signal}:{label:string;value:string;signal:Signal}){return <div className={cn("border border-border border-t-2 bg-card p-3",statusMeta[signal].classes)}><div className="text-[11px] font-semibold uppercase text-muted-foreground">{label}</div><div className="mt-2 whitespace-nowrap font-mono text-xl font-medium tabular-nums">{value}</div><div className="mt-1 text-[11px]">{statusMeta[signal].label}</div></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="border border-border bg-card p-4"><h2 className="mb-3 font-semibold">{title}</h2>{children}</section>}
function InfoRow({k,v}:{k:string;v:string}){return <div className="flex justify-between gap-4 border-t border-border py-2 text-sm first:border-0"><span className="text-muted-foreground">{k}</span><span className="text-right font-medium">{v}</span></div>}

function MachinePanel({patient}:{patient:Patient}){return <section className="border border-machine bg-machine-soft p-4"><MachineMark verb="Detected" confidence="High"/><h2 className="mt-3 font-semibold">Change from this patient’s recent pattern</h2><p className="mt-1 text-sm leading-relaxed">{patient.reason}. This observation pattern meets the prototype rapid-review rule; it does not diagnose a condition.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div><div className="text-[11px] uppercase text-muted-foreground">Physiology</div><div className="font-mono text-lg">42 / 45</div></div><div><div className="text-[11px] uppercase text-muted-foreground">Trend + symptoms</div><div className="font-mono text-lg">31 / 35</div></div><div><div className="text-[11px] uppercase text-muted-foreground">Context + quality</div><div className="font-mono text-lg">9 / 20</div></div></div><div className="mt-4 border-t border-machine/30 pt-3 font-mono text-[11px] text-muted-foreground">8 readings · LN-SP02-0418 · paired 10 Sep 2026 · rule v0.8.3 · NEWS2-like prototype</div></section>}

function AlertView({patient,onView,notify}:{patient:Patient;onView:(v:View)=>void;notify:(s:string)=>void}){const [owner,setOwner]=useState(false);const [decision,setDecision]=useState("Repeat observations in 10 minutes");return <><PageHead eyebrow="Alert review · ALT-20418" title="Rapid response review" summary={`${patient.name} · Opened 08:44 AEST · 5 minutes elapsed`} actions={<Button variant="outline" onClick={()=>onView("patient")}><ChevronLeft/>Patient record</Button>}/><div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1.2fr)_420px] lg:p-8"><div className="space-y-5"><div className="border-l-2 border-rapid bg-rapid-soft p-4"><SignalBadge signal="rapid"/><h2 className="mt-3 text-lg font-semibold">SpO₂ 88% and respiratory rate 28 /min</h2><p className="mt-1 text-sm">Outside pathway range across two observations. Increased work of breathing reported at 08:40 AEST.</p></div><MachinePanel patient={patient}/><Panel title="Source observations"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Vital label="SpO₂" value="88 %" signal="rapid"/><Vital label="Resp. rate" value="28 /min" signal="rapid"/><Vital label="Heart rate" value="112 bpm" signal="review"/><Vital label="Signal quality" value="Good" signal="stable"/></div></Panel><Panel title="Linked alert history"><InfoRow k="12 Sep · 19:10" v="Clinical review · resolved after repeat"/><InfoRow k="11 Sep · 07:45" v="No data · device re-paired"/></Panel></div><aside><Panel title="Disposition required"><label className="block text-xs font-semibold uppercase text-muted-foreground">Clinical decision</label><select value={decision} onChange={e=>setDecision(e.target.value)} className="mt-2 h-11 w-full rounded-control border border-input bg-background px-3 text-sm"><option>Repeat observations in 10 minutes</option><option>Urgent video assessment</option><option>Escalate to rapid response</option><option>Transfer to hospital</option></select><label className="mt-4 block text-xs font-semibold uppercase text-muted-foreground">Clinical note</label><textarea className="mt-2 min-h-28 w-full rounded-control border border-input bg-background p-3 text-sm" defaultValue="Reviewed trend and symptoms. Patient contacted; repeat observations requested while physician joins call."/><div className="mt-4 border border-border bg-muted p-3 text-xs"><strong>Safety requirement</strong><p className="mt-1 text-muted-foreground">An owner, action, due time and final disposition are required. Machine output cannot close this alert.</p></div><Button className="mt-4 w-full" onClick={()=>{setOwner(true);notify(`Alert owned; ${decision}`)}} disabled={owner}>{owner?"Owned by Noah Williams":"Take ownership"}</Button><Button variant="outline" className="mt-2 w-full" onClick={()=>onView("handover")}><Ambulance/>Escalate and prepare handover</Button></Panel></aside></div></>}

function HandoverView({patient,onView,notify}:{patient:Patient;onView:(v:View)=>void;notify:(s:string)=>void}){const [sent,setSent]=useState(false);return <><PageHead eyebrow="Structured transfer" title="Emergency handover" summary={`${patient.name} · Drafted, not sent · Minimum necessary information`} actions={<Button variant="outline" onClick={()=>onView("alert")}><ChevronLeft/>Alert</Button>}/><div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1.3fr)_380px] lg:p-8"><div className="border border-machine bg-card"><div className="border-b border-machine bg-machine-soft p-4"><MachineMark verb="Drafted — not sent" confidence="High"/><p className="mt-2 text-xs text-muted-foreground">Generated from 8 observations, active pathway, current medicines and clinician note.</p></div>{[["Situation",`${patient.name}, ${patient.age}, is receiving hospital-level care at home for ${patient.diagnosis}. Rapid response opened at 08:44 AEST.`],["Background","Respiratory virtual ward since 10 Sep. Home oxygen prescribed. Previous no-data alert resolved after device re-pairing."],["Assessment","SpO₂ declined from 94% to 88%; respiratory rate 28 /min; heart rate 112 bpm. Increased work of breathing reported."],["Recommendation","Urgent transfer for in-person assessment. Continue oxygen as prescribed while transport arrives. Named clinician remains available."]].map(([h,t])=><section key={h} className="border-b border-border p-5"><h2 className="text-xs font-semibold uppercase text-primary">{h}</h2><p className="mt-2 text-sm leading-relaxed">{t}</p></section>)}</div><aside className="space-y-4"><Panel title="Transfer checklist">{["Identity confirmed","Goals of care checked","Allergies included","Medicines reconciled","Address and access notes","Named clinical contact"].map(x=><label key={x} className="flex min-h-10 items-center gap-3 border-t border-border text-sm first:border-0"><input type="checkbox" defaultChecked className="size-4 accent-primary"/>{x}</label>)}</Panel><Panel title="Receiving service"><InfoRow k="Destination" v="Metro South ED"/><InfoRow k="Transport" v="Metro Ambulance"/><InfoRow k="Priority" v="Time critical"/><InfoRow k="Access expiry" v="10:49 AEST"/><Button className="mt-4 w-full" onClick={()=>{setSent(true);notify("Simulated handover sent to Metro Ambulance")}} disabled={sent}>{sent?"Sent · awaiting acknowledgement":"Send simulated handover"}</Button><Button variant="outline" className="mt-2 w-full" onClick={()=>onView("emergency")}>Preview emergency portal</Button></Panel></aside></div></>}

function ScenariosView({notify,onOpen}:{notify:(s:string)=>void;onOpen:()=>void}){const [running,setRunning]=useState<number|null>(null);return <><PageHead eyebrow="Prototype control" title="Scenario control" summary="Deterministic, resettable demonstration events." actions={<Button variant="outline" onClick={()=>{setRunning(null);notify("All scenarios reset to baseline")}}><RotateCcw/>Reset all</Button>}/><div className="p-5 lg:p-8"><div className="grid gap-3 xl:grid-cols-2">{scenarios.map((s,i)=><div key={s[0]} className={cn("border bg-card p-5",running===i?"border-machine":"border-border")}><div className="flex items-start gap-4"><div className={cn("grid size-10 shrink-0 place-items-center border",running===i?"border-machine bg-machine-soft text-machine":"border-border bg-muted text-primary")}>{running===i?<Radio/>:<Play/>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{s[0]}</h2><p className="text-xs text-muted-foreground">{s[1]} · {s[3]}</p></div><span className={cn("text-xs font-semibold",running===i?"text-machine":"text-muted-foreground")}>{running===i?"RUNNING":"READY"}</span></div><p className="mt-3 text-sm">{s[2]}</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={()=>{setRunning(running===i?null:i);notify(running===i?`${s[0]} paused`:`${s[0]} started`)}}>{running===i?<><Pause/>Pause</>:<><Play/>Run scenario</>}</Button>{i===0&&<Button size="sm" variant="outline" onClick={onOpen}>Open patient</Button>}</div></div></div></div>)}</div></div></>}

function GovernanceView({auditEvents}:{auditEvents:Array<[string,string,string,string,string]>}){const events=[...auditEvents,["08:49:12","Noah Williams","Alert acknowledged","ALT-20418","Console"],["08:44:03","Rātana rules","Rapid response created","pat-1001","v0.8.3"],["08:43:57","Rātana model","Concern ranking updated","pat-1001","model v0.4"],["08:42:10","LN-SP02-0418","Observation received","pat-1001","Device paired 10 Sep"],["08:31:46","Leo Morgan","Patient note recorded","pat-1003","Console"]];return <><PageHead eyebrow="Safety & quality" title="Governance dashboard" summary="Operational performance · 1–13 September 2026"/><div className="space-y-5 p-5 lg:p-8"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Alerts acknowledged" value="98.2%" detail="Within 5 minutes"/><Metric label="Median response" value="03:42" detail="Rapid response alerts"/><Metric label="Escalations" value="214" detail="4.8% of episodes"/><Metric label="Device reliability" value="97.6%" detail="Expected observations"/></div><div className="grid gap-5 lg:grid-cols-2"><Panel title="Alert outcomes"><GovernanceBar label="Resolved after intervention" value={58}/><GovernanceBar label="Transferred to hospital" value={22}/><GovernanceBar label="Repeat measurement / artifact" value={13}/><GovernanceBar label="Other documented outcome" value={7}/></Panel><Panel title="Safety controls"><InfoRow k="Unowned rapid alerts" v="12"/><InfoRow k="Overdue No data outreach" v="31"/><InfoRow k="Machine service availability" v="99.3%"/><InfoRow k="Current rule version" v="v0.8.3"/><InfoRow k="Access reviews due" v="7"/></Panel></div><div className="overflow-x-auto border border-border bg-card"><div className="border-b border-border p-4"><h2 className="font-semibold">Recent auditable events</h2></div><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-muted text-[11px] uppercase text-muted-foreground"><tr><th className="px-4 py-3">Time</th><th>Actor</th><th>Event</th><th>Subject</th><th>Version / source</th></tr></thead><tbody>{events.map((r,index)=><tr key={`${r.join()}-${index}`} className="h-12 border-t border-border">{r.map((c,i)=><td key={`${c}-${i}`} className={cn(i===0||i===4?"font-mono":"",i===0&&"px-4")}>{c}</td>)}</tr>)}</tbody></table></div></div></>}
function GovernanceBar({label,value}:{label:string;value:number}){return <div className="mb-4"><div className="mb-1 flex justify-between text-sm"><span>{label}</span><span className="font-mono">{value}%</span></div><div className="h-2 bg-muted"><div className="h-full bg-primary" style={{width:`${value}%`}}/></div></div>}

function UsersView({notify}:{notify:(s:string)=>void}){const [invited,setInvited]=useState(false);return <><PageHead eyebrow="Identity & access" title="Users and access" summary="Role, organization, region, team and expiry govern every account." actions={<Button onClick={()=>{setInvited(true);notify("Invitation created")}} disabled={invited}><Users/>{invited?"Invitation created":"Invite user"}</Button>}/><div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_340px] lg:p-8"><div className="overflow-x-auto border border-border bg-card"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-muted text-[11px] uppercase text-muted-foreground"><tr><th className="px-4 py-3">Person</th><th>Role</th><th>Scope</th><th>Status</th><th>Last access</th><th></th></tr></thead><tbody>{[["Dr Asha Rao","Consultant","Metro South · Respiratory Blue","Active","08:48"],["Mia Chen","Visiting nurse","Metro North · Cardiac West","Active","08:43"],["Grace Mensah","Governance lead","All regions","Active","Yesterday"],["Amir Haddad","Device support","Device metadata only","Active","08:22"],["Ambulance liaison","Emergency services","pat-1001 · expires 10:49","Time limited","Never"]].map(r=><tr key={r[0]} className="h-14 border-t border-border"><td className="px-4 font-semibold">{r[0]}</td><td>{r[1]}</td><td className="text-xs text-muted-foreground">{r[2]}</td><td><span className="border border-primary px-2 py-1 text-xs text-primary">{r[3]}</span></td><td className="font-mono text-xs">{r[4]}</td><td><Button variant="ghost" size="icon" aria-label={`Manage ${r[0]}`}><Settings2/></Button></td></tr>)}</tbody></table></div><Panel title="Access safeguards"><InfoRow k="Pending invitations" v={invited?"4":"3"}/><InfoRow k="Expiring in 24 h" v="5"/><InfoRow k="Suspended accounts" v="2"/><InfoRow k="Access reviews due" v="7"/><p className="mt-4 border-t border-border pt-4 text-xs text-muted-foreground">Emergency and proxy access is patient-scoped, time-limited and audited. Device support cannot view clinical notes.</p></Panel></div></>}

function EmergencyView({patient,notify}:{patient:Patient;notify:(s:string)=>void}){const [ack,setAck]=useState(false);return <div className="min-h-[calc(100vh-56px)] bg-card"><div className="border-b border-rapid bg-rapid-soft px-5 py-3 text-sm text-rapid"><strong>Time-limited emergency access</strong> · Expires 10:49 AEST · Every view is audited</div><PageHead eyebrow="Metro Ambulance · Case TR-8841" title={`Handover: ${patient.name}`} summary="Minimum necessary information for this active transfer" actions={<SignalBadge signal="rapid"/>}/><div className="mx-auto grid max-w-6xl gap-5 p-5 lg:grid-cols-[1fr_360px] lg:p-8"><div className="space-y-5"><Panel title="Immediate situation"><p className="text-lg">COPD exacerbation with SpO₂ 88% and respiratory rate 28 /min. Increased work of breathing.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Vital label="SpO₂" value="88 %" signal="rapid"/><Vital label="Resp. rate" value="28 /min" signal="rapid"/><Vital label="Heart rate" value="112 bpm" signal="review"/><Vital label="BP systolic" value="104 mmHg" signal="stable"/></div></Panel><Panel title="Access and safety"><InfoRow k="Home access" v="Front ramp · carer present"/><InfoRow k="Allergies" v="Penicillin · rash"/><InfoRow k="Goals of care" v="Active treatment"/><InfoRow k="Infection risk" v="Standard precautions"/><InfoRow k="Clinical contact" v="Dr Asha Rao · in-app call"/></Panel></div><Panel title="Transport response"><InfoRow k="Requested" v="08:51 AEST"/><InfoRow k="Priority" v="Time critical"/><InfoRow k="Destination" v="Metro South ED"/><label className="mt-4 block text-xs font-semibold uppercase text-muted-foreground">Estimated arrival</label><select className="mt-2 h-11 w-full rounded-control border border-input bg-background px-3"><option>10–15 minutes</option><option>15–25 minutes</option><option>25–40 minutes</option></select><Button className="mt-4 w-full" onClick={()=>{setAck(true);notify("Handover acknowledged by Ambulance liaison")}} disabled={ack}>{ack?"Acknowledged · 08:52":"Acknowledge handover"}</Button></Panel></div></div>}

function AdmissionView({notify}:{notify:(s:string)=>void}){const [tab,setTab]=useState<"admission"|"discharge">("admission");const [done,setDone]=useState(false);return <><PageHead eyebrow="Episode management" title="Admission and discharge" summary="Clinician-controlled safety checks for entry to and exit from Hospital in the Home." actions={<div className="flex border border-border"><Button variant={tab==="admission"?"default":"ghost"} onClick={()=>setTab("admission")}>Admission</Button><Button variant={tab==="discharge"?"default":"ghost"} onClick={()=>setTab("discharge")}>Discharge</Button></div>}/><div className="mx-auto max-w-5xl p-5 lg:p-8"><div className="grid gap-5 lg:grid-cols-[1fr_330px]"><Panel title={tab==="admission"?"Admission safety checklist":"Discharge readiness review"}>{(tab==="admission"?["Patient identity and consent confirmed","Clinical eligibility reviewed by admitting clinician","Home environment and service zone suitable","Caregiver availability recorded","Device kit assigned and paired","Monitoring schedule and escalation plan explained"]:["Observations stable within pathway range","No unresolved alerts or overdue tasks","Medicines and follow-up plan reconciled","Patient and caregiver understand return precautions","Equipment return arranged","Receiving primary care team notified"]).map((x,i)=><label key={x} className="flex min-h-14 items-center gap-3 border-t border-border text-sm first:border-0"><input type="checkbox" defaultChecked={i<4} className="size-5 accent-primary"/><span className="flex-1">{x}</span>{i<4&&<span className="font-mono text-[11px] text-muted-foreground">08:{12+i*3} AEST</span>}</label>)}</Panel><aside className="space-y-4"><Panel title={tab==="admission"?"Episode setup":"Advisory readiness"}>{tab==="admission"?<><InfoRow k="Patient" v="Mei Tan"/><InfoRow k="Pathway" v="Respiratory virtual ward"/><InfoRow k="First visit" v="13 Sep · 10:30"/><InfoRow k="Device kit" v="KIT-2217"/></>:<><MachineMark verb="Summarised" confidence="Moderate"/><p className="my-3 text-sm">5 of 6 criteria appear complete. Equipment return remains unconfirmed.</p><InfoRow k="Readiness score" v="83 / 100"/><InfoRow k="Clinician decision" v="Required"/></>}<Button className="mt-4 w-full" onClick={()=>{setDone(true);notify(`${tab==="admission"?"Admission":"Discharge"} recorded in episode`)}} disabled={done}>{done?"Recorded":"Clinician confirm"}</Button></Panel></aside></div></div></>}

function PatientSurface({view,onView,onExit,notify}:{view:View;onView:(v:View)=>void;onExit:()=>void;notify:(s:string)=>void}){const [help,setHelp]=useState(false);const [step,setStep]=useState(0);if(view==="observation")return <div className="min-h-screen bg-lamplight text-night"><PatientHeader onExit={onExit}/><main className="mx-auto max-w-xl px-5 pb-10 pt-7"><Button variant="ghost" onClick={()=>onView("patientapp")}><ChevronLeft/>Back</Button><div className="mt-5 text-xs font-semibold uppercase text-primary">Daily check · step {Math.min(step+1,3)} of 3</div><h1 className="mt-2 font-display text-4xl font-semibold">{step===0?"Record your oxygen level":step===1?"How are you feeling?":"Your check is complete"}</h1><p className="mt-3 text-lg leading-relaxed">{step===0?"Sit comfortably and keep your hand still. Your pulse oximeter is connected.":step===1?"Choose any changes you have noticed today.":"Your care team can now see these readings."}</p>{step===0&&<div className="my-8 border border-lamplight-edge bg-card p-6"><div className="flex items-center gap-3 text-primary"><Radio/><span className="font-semibold">LN-SP02-0418 connected</span></div><div className="mt-8 text-center"><div className="font-mono text-5xl tabular-nums">96 %</div><div className="mt-2 text-lg">In your usual range</div></div></div>}{step===1&&<div className="my-8 space-y-3">{["More breathless than usual","Chest discomfort","Dizzy or faint","No new symptoms"].map((x,i)=><label key={x} className="flex min-h-14 items-center gap-4 border border-lamplight-edge bg-card px-4 text-lg"><input type="checkbox" defaultChecked={i===3} className="size-5 accent-primary"/>{x}</label>)}</div>}{step===2&&<div className="my-8 border border-stable bg-stable-soft p-6 text-center"><div className="mx-auto grid size-12 place-items-center rounded-full bg-stable text-primary-foreground"><Check/></div><h2 className="mt-4 font-display text-2xl">Readings received</h2><p className="mt-2">Sam, your nurse, will review them by 10:00.</p></div>}<Button variant="patient" size="patient" className="w-full" onClick={()=>{if(step<2)setStep(step+1);else{notify("Observation received by care team");onView("patientapp")}}}>{step<2?"Continue":"Return home"}</Button></main></div>;
  return <div className="min-h-screen bg-lamplight text-night"><PatientHeader onExit={onExit}/><main className="mx-auto max-w-xl px-5 pb-32 pt-8"><p className="text-lg">Good morning, Mei.</p><h1 className="mt-1 font-display text-4xl font-semibold">Your care at home</h1><p className="mt-2 text-lg">Day 4 of your respiratory care plan</p><section className="mt-8 border border-lamplight-edge bg-card p-5"><div className="flex justify-between"><div><h2 className="font-display text-2xl font-semibold">Today</h2><p className="mt-1 text-base">2 of 4 tasks complete</p></div><span className="font-mono text-sm">13 SEP</span></div>{[["Morning medicines","08:00 · Completed",true],["Record oxygen level","Due now",false],["Video visit with Sam","10:30",false],["Evening medicines","18:00",true]].map(([a,b,c])=><div key={String(a)} className="flex min-h-16 items-center gap-4 border-t border-lamplight-edge"><span className={cn("grid size-7 place-items-center rounded-full border",c?"border-stable bg-stable text-primary-foreground":"border-primary text-primary")}>{c?<Check className="size-4"/>:<Clock3 className="size-4"/>}</span><div className="flex-1"><div className="text-lg font-medium">{a}</div><div className="text-sm text-muted-foreground">{b}</div></div>{!c&&a==="Record oxygen level"&&<Button variant="outline" onClick={()=>onView("observation")}>Start</Button>}</div>)}</section><section className="mt-5 border border-review bg-review-soft p-5"><SignalBadge signal="review"/><h2 className="mt-3 font-display text-2xl font-semibold">Your care team is checking a change</h2><p className="mt-2 text-lg leading-relaxed">Sam, your nurse, will call you by 10:00. Keep following your care plan unless they tell you otherwise.</p></section><section className="mt-5 grid grid-cols-2 gap-3"><div className="border border-lamplight-edge bg-card p-4"><Wind className="text-primary"/><div className="mt-4 font-mono text-3xl">96 %</div><div className="mt-1">Oxygen level · usual range</div></div><div className="border border-lamplight-edge bg-card p-4"><Thermometer className="text-primary"/><div className="mt-4 font-mono text-3xl">36.8 °C</div><div className="mt-1">Temperature · usual range</div></div></section></main><div className="fixed inset-x-0 bottom-0 border-t border-lamplight-edge bg-lamplight p-4"><Button variant="patient" size="patient" className="mx-auto w-full max-w-xl" onClick={()=>{setHelp(true);notify("Help request sent to Sam Webb")}} disabled={help}><HeartPulse/>{help?"Sam will call by 09:05":"I need help now"}</Button></div></div>}
function PatientHeader({onExit}:{onExit:()=>void}){return <header className="flex h-16 items-center border-b border-lamplight-edge px-5"><Brand/><Button variant="ghost" className="ml-auto" onClick={onExit}>Clinical demo</Button></header>}